[package]
name = "atop"
version = "0.1.2"
edition = "2021"
authors = ["Petter K <ermines-bookie-0l@icloud.com>"]
description = "Top alternative that shows average CPU usage"
license = "Apache-2.0"

[dependencies]
sysinfo = "0.20.5"

[[bin]]
name = "atop"
path = "src/main.rs"
