name: Build, test and publish (Main)

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Set Version in Cargo.toml
      run: |
        LATEST_TAG=$(git describe --tags --abbrev=0)

        if [[ $LATEST_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          VERSION=${LATEST_TAG#v}  # Remove 'v' prefix
          sed -i "s/version = \".*\"/version = \"$VERSION\"/" Cargo.toml
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Cargo.toml
          git commit -m "Set version to $VERSION"
          git push origin
        else
          echo "Invalid SemVer tag."
          exit 1
        fi

    - name: Publish
      run: cargo publish --verbose --token ${{ secrets.CARGO_KEY }}
